targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/*.dart
        options:
          map: false
          when: false
      riverpod_generator:
        generate_for:
          include:
            - lib/**/*.dart
      go_router_builder:
        generate_for:
          include:
            - lib/router.dart
      json_serializable:
        generate_for:
          include:
            - lib/**/*.dart
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true