name: quick_internet_client
description: "Mobile app for https://sizu.me"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  logger: any
  retrofit: ^4.0.3
  riverpod_annotation: ^2.0.0

dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  freezed: ^2.2.0
  json_serializable: ^6.6.2
  pedantic_mono: ^1.25.0
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - .env